/* =============================================================
   mantis_plants_data.js
   Mantis Gardens — Plant & Fertilizer Data
   Edit this file to update plant and fertilizer/spray info.
   ============================================================= */

// =============================================================
// PLANT DATA  (24 plants)
// =============================================================
const PLANTS = [
  // ── California Natives ──────────────────────────────────────
  { common:"Ceanothus",          latin:"Ceanothus spp.",               category:"California Native",
    water:"Low–moderate once established", sun:"Full sun to part shade",
    size:"3–12 ft depending on variety",  deer:"Moderate resistance",
    notes:"Blooms blue/purple spring. Excellent habitat plant. Do not overwater — root rot risk.",
    tags:["native","drought"] },
  { common:"Manzanita",          latin:"Arctostaphylos spp.",          category:"California Native",
    water:"Very low once established",     sun:"Full sun",
    size:"2–15 ft depending on variety",  deer:"Good resistance",
    notes:"Striking bark. Winter/spring blooms. Needs excellent drainage. Do not summer water established plants.",
    tags:["native","drought","deer"] },
  { common:"California Poppy",   latin:"Eschscholzia californica",     category:"California Native",
    water:"Very low",                      sun:"Full sun",
    size:"6–12 inches",                    deer:"Good resistance",
    notes:"Annual/perennial. Self-seeds freely. Do not remove seedlings unless instructed by client.",
    tags:["native","drought"] },
  { common:"Buckwheat",          latin:"Eriogonum spp.",               category:"California Native",
    water:"Very low once established",     sun:"Full sun",
    size:"1–4 ft",                         deer:"Good resistance",
    notes:"Excellent pollinator plant. Flowers dry to rusty orange — often kept for winter interest.",
    tags:["native","drought","deer"] },
  { common:"Salvia (native)",    latin:"Salvia spp. (CA native)",      category:"California Native",
    water:"Low once established",          sun:"Full sun to part shade",
    size:"2–6 ft",                         deer:"Excellent resistance",
    notes:"Fragrant foliage. Cut back by 1/3 after bloom. Many species attract hummingbirds.",
    tags:["native","drought","deer"] },
  { common:"Sphaeralcea (Globe Mallow)", latin:"Sphaeralcea spp.",     category:"California Native",
    water:"Very low",                      sun:"Full sun",
    size:"2–4 ft",                         deer:"Good resistance",
    notes:"Apricot/orange blooms. Up-pot from 1gal to 5gal using Native Mix (3:1 cactus bulk:EB Stone + 5% compost + 1/4\" worm castings).",
    tags:["native","drought"] },
  { common:"Sedum 'Autumn Joy'", latin:"Hylotelephium telephium",      category:"Succulent / Xeric",
    water:"Low",                           sun:"Full sun",
    size:"18–24 inches",                   deer:"Good resistance",
    notes:"Late summer pink blooms turn coppery in fall. Cut back to ground in late winter.",
    tags:["drought","deer"] },

  // ── Mediterranean / Xeric ───────────────────────────────────
  { common:"Lavender",           latin:"Lavandula spp.",               category:"Mediterranean / Xeric",
    water:"Low once established",          sun:"Full sun",
    size:"1–4 ft",                         deer:"Excellent resistance",
    notes:"Prune by 1/3 after bloom. Do not cut into woody stems. Spanish types bloom longer; English types more fragrant.",
    tags:["drought","deer"] },
  { common:"Rosemary",           latin:"Salvia rosmarinus",            category:"Mediterranean / Xeric",
    water:"Low once established",          sun:"Full sun",
    size:"2–6 ft",                         deer:"Excellent resistance",
    notes:"Prune lightly after bloom. Excellent hedge plant. Do not overwater — susceptible to root rot in clay.",
    tags:["drought","deer"] },
  { common:"Cistus (Rock Rose)", latin:"Cistus spp.",                  category:"Mediterranean / Xeric",
    water:"Very low once established",     sun:"Full sun",
    size:"2–5 ft",                         deer:"Good resistance",
    notes:"Short-lived blooms spring–summer. Do not prune hard. Replace every 8–10 years.",
    tags:["drought","deer"] },
  { common:"Echium",             latin:"Echium wildprettii",           category:"Mediterranean / Xeric",
    water:"Low",                           sun:"Full sun",
    size:"6–10 ft (tower form)",           deer:"Moderate resistance",
    notes:"Dramatic tower of bloom. Biennial — dies after blooming, self-seeds. Install from 1gal.",
    tags:["drought"] },
  { common:"Bulbine",            latin:"Bulbine frutescens",           category:"Mediterranean / Xeric",
    water:"Low",                           sun:"Full sun to part shade",
    size:"12–18 inches",                   deer:"Good resistance",
    notes:"Orange or yellow blooms nearly year-round. Cut back in late winter to refresh.",
    tags:["drought","deer"] },
  { common:"Bougainvillea",      latin:"Bougainvillea spp.",           category:"Mediterranean / Xeric",
    water:"Low–moderate",                  sun:"Full sun",
    size:"10–30 ft (vine/shrub)",          deer:"Good resistance",
    notes:"Thorny. Heavy bloomers in heat and drought stress. Reduce water in summer to promote flowering. Frost sensitive.",
    tags:["drought"] },

  // ── Fruit & Edible ──────────────────────────────────────────
  { common:"Citrus (general)",   latin:"Citrus spp.",                  category:"Fruit & Edible",
    water:"Moderate",                      sun:"Full sun",
    size:"8–20 ft",                        deer:"Low resistance",
    notes:"Feed with Urban Farms liquid + CitrusTone granular. Sacramento watering days apply. See citrus pruning video link in loading sheet.",
    tags:["fruit"] },
  { common:"Peach 'Blenheim'",   latin:"Prunus persica 'Blenheim'",   category:"Fruit & Edible",
    water:"Moderate",                      sun:"Full sun",
    size:"15–20 ft",                       deer:"Low resistance",
    notes:"Prune in dormant season only. Apply sulfur/hort oil spray after pruning. Classic Sacramento variety.",
    tags:["fruit"] },
  { common:"Apricot 'Tomcot'",   latin:"Prunus armeniaca 'Tomcot'",   category:"Fruit & Edible",
    water:"Low–moderate",                  sun:"Full sun",
    size:"15–20 ft",                       deer:"Low resistance",
    notes:"Do NOT use sulfur/hort oil spray on apricot — can cause phytotoxicity. Prune after harvest.",
    tags:["fruit","warn"] },
  { common:"Fig",                latin:"Ficus carica",                 category:"Fruit & Edible",
    water:"Low–moderate once established", sun:"Full sun",
    size:"10–30 ft",                       deer:"Moderate resistance",
    notes:"Aggressive root system. Prune in dormant season. Milky sap can irritate skin — wear gloves.",
    tags:["fruit"] },

  // ── Ornamental Shrubs & Trees ───────────────────────────────
  { common:"Japanese Maple",     latin:"Acer palmatum",               category:"Ornamental Trees & Shrubs",
    water:"Moderate",                      sun:"Part shade (Sacramento heat)",
    size:"6–25 ft",                        deer:"Low resistance",
    notes:"Feed with Maxsea Acid + acidifier. Protect from afternoon sun. Do not prune in spring.",
    tags:["shade"] },
  { common:"Camellia",           latin:"Camellia spp.",               category:"Ornamental Trees & Shrubs",
    water:"Moderate",                      sun:"Part shade",
    size:"6–15 ft",                        deer:"Moderate resistance",
    notes:"Feed with HollyTone or Maxsea Acid. Acidic soil required. Prune immediately after bloom.",
    tags:["shade"] },
  { common:"Azalea / Rhododendron", latin:"Rhododendron spp.",        category:"Ornamental Trees & Shrubs",
    water:"Moderate",                      sun:"Part shade",
    size:"3–10 ft",                        deer:"Moderate resistance",
    notes:"Feed with HollyTone or acid fertilizer. Need excellent drainage and acidic soil. Deer browse when young.",
    tags:["shade"] },
  { common:"Rose",               latin:"Rosa spp.",                   category:"Ornamental Trees & Shrubs",
    water:"Moderate–high",                 sun:"Full sun (6+ hrs)",
    size:"3–15 ft depending on type",      deer:"Low resistance",
    notes:"Apply sulfur/hort oil after dormant pruning. Feed with RoseTone. Wear rose gloves when pruning. David Austin climbers: minimal pruning first 2 years.",
    tags:["rose"] },
  { common:"Photinia",           latin:"Photinia x fraseri",          category:"Ornamental Trees & Shrubs",
    water:"Low–moderate",                  sun:"Full sun to part shade",
    size:"8–15 ft",                        deer:"Moderate resistance",
    notes:"Prune walkthrough required with David on first visit. Red new growth is the ornamental feature.",
    tags:[] },
  { common:"Privet (topiary)",   latin:"Ligustrum spp.",              category:"Ornamental Trees & Shrubs",
    water:"Low–moderate",                  sun:"Full sun to part shade",
    size:"Variable — maintain to shape",   deer:"Low resistance",
    notes:"Maintain topiary/tree form per client instruction. Front 3-tier topiary: prune seasonally.",
    tags:[] },
  { common:"Atlas Cedar",        latin:"Cedrus atlantica",            category:"Ornamental Trees & Shrubs",
    water:"Low once established",          sun:"Full sun",
    size:"40–60 ft (tree)",               deer:"Good resistance",
    notes:"Property management handles all tree pruning unless otherwise noted by client.",
    tags:["drought","deer"] },
];

// =============================================================


// =============================================================
// FERTILIZER & SPRAY DATA  (17 products)
// =============================================================
const FERT_PRODUCTS = [
  // Liquid fertilizers
  { name:"Urban Farms Liquid Fertilizer", abbrev:"UF", type:"Liquid Fertilizer",
    npk:"4-3-3 (approx.)", use:"Citrus, in-ground and potted. General feeding.",
    rate:"2.5–10 gal per application depending on plant size",
    timing:"Year-round except deep winter. Reduce in Dec–Jan.",
    notes:"Primary all-purpose liquid for citrus and guava. Water in after application.",
    category:"fertilizer" },
  { name:"Maxsea: Grow",   abbrev:"MG",  type:"Liquid Fertilizer (seaweed)",
    npk:"16-16-16", use:"Potted plants, general growth phase",
    rate:"1 tbsp per gallon of water, apply to saturation",
    timing:"Spring through mid-summer",
    notes:"Seaweed-based. Excellent for general potted plant feeding.",
    category:"fertilizer" },
  { name:"Maxsea: Acid",   abbrev:"MA",  type:"Liquid Fertilizer (seaweed)",
    npk:"14-18-14", use:"Acid-loving plants: Japanese maple, azalea, camellia, rhododendron, blueberry",
    rate:"1 tbsp per gallon + acidifier as needed",
    timing:"Spring and early summer",
    notes:"Use with acidifier for Japanese maples. Feed before budbreak for best results.",
    category:"fertilizer" },
  { name:"Maxsea: Bloom",  abbrev:"MB",  type:"Liquid Fertilizer (seaweed)",
    npk:"3-20-20", use:"Flowering plants during bloom phase",
    rate:"1 tbsp per gallon of water",
    timing:"When flower buds are setting",
    notes:"High phosphorus/potassium promotes flowering. Switch from Grow to Bloom mid-summer.",
    category:"fertilizer" },

  // Granular fertilizers
  { name:"CitrusTone",     abbrev:"CT",  type:"Granular Fertilizer",
    npk:"5-2-6", use:"Citrus trees — all types",
    rate:"Potted: 2–3 cups. In-ground: 6 cups per large tree",
    timing:"March through September. Remove weed cloth before applying.",
    notes:"Water in heavily after application. Do not apply on driveways — stains.",
    category:"fertilizer" },
  { name:"HollyTone",      abbrev:"HT",  type:"Granular Fertilizer",
    npk:"4-3-4", use:"Acid-loving plants: azalea, camellia, rhododendron, blueberry, gardenia",
    rate:"Per plant label. Top-dress and water in.",
    timing:"Spring and fall",
    notes:"Acidifying formula. Alternative to Maxsea Acid for larger plants.",
    category:"fertilizer" },
  { name:"RoseTone",       abbrev:"RT",  type:"Granular Fertilizer",
    npk:"4-3-2", use:"Roses — all types",
    rate:"Climbing rose: 5gal MG + 3 cups RT. Per plant label for others.",
    timing:"Early spring through August. Stop 6 weeks before first frost.",
    notes:"Water in after application. Use with Maxsea for climbing roses.",
    category:"fertilizer" },
  { name:"BioTone Starter", abbrev:"BT", type:"Granular Fertilizer / Soil Inoculant",
    npk:"4-3-3 + mycorrhizae", use:"New plantings — all types",
    rate:"1/2 cup in planting hole + 1 cup top-dress after planting",
    timing:"At time of planting only",
    notes:"Mycorrhizal inoculant promotes root development. Mix into backfill. Top-dress after watering in.",
    category:"fertilizer" },

  // Soil amendments
  { name:"Worm Castings",  abbrev:"WC",  type:"Soil Amendment",
    npk:"1-0-0 (trace)", use:"All plantings — mixed into native soil mixes and top-dress",
    rate:"1/4\" layer in soil mix or 1 cup per plant as top-dress",
    timing:"At planting or spring top-dress",
    notes:"Part of Native Mix: 3:1 Cactus bulk:EB Stone Cactus mix + 5% compost + 1/4\" worm castings.",
    category:"amendment" },
  { name:"EB Stone Cactus Mix", abbrev:"—", type:"Soil Amendment",
    npk:"N/A", use:"CA natives, succulents, xeric plants",
    rate:"Component of Native Mix (see Worm Castings)",
    timing:"At planting",
    notes:"Native Mix = 3:1 Cactus bulk:EB Stone Cactus + 5% compost + 1/4\" worm castings. Xeric/succulent mix = 5:1:1 Cactus Mix:Topsoil:EB Stone.",
    category:"amendment" },
  { name:"Compost (bulk)",  abbrev:"—",  type:"Soil Amendment",
    npk:"Variable", use:"All new plantings — soil amendment and top-dress",
    rate:"50% site-soil / 50% compost for most installs. 5% additive in Native Mix.",
    timing:"At planting",
    notes:"Arbor mulch used for top-dress after planting. 15–35gal tote loaded per job.",
    category:"amendment" },

  // Sprays & pest control
  { name:"Sulfur / Hort Oil (Dormant Spray)", abbrev:"SHO", type:"Dormant Spray",
    npk:"N/A",
    use:"Roses, deciduous trees, woody deciduous shrubs — dormant season only",
    rate:"Sulfur: 1 tbsp/gal · Hort oil: 1.5 tbsp/gal · Mixed together in sprayer",
    timing:"Immediately after dormant pruning. Hard end date: March 1 (earlier if warm winter).",
    notes:"Kills insect eggs, mites, microscopic pests. Inhibits fungal/bacterial growth on fresh cuts. Shake vigorously — sulfur settles. Rinse sprayer weekly with Dawn/Castille soap. CAUTION: irritant to eyes/skin — rinse with water. Billable: 1/4 gal minimum.",
    category:"spray", warn:true },
  { name:"Isopropyl Dip",   abbrev:"IPA", type:"Sanitation Spray",
    npk:"N/A", use:"Pruning tools between cuts — especially on diseased material",
    rate:"Dip or spray tool blades between cuts",
    timing:"Any time pruning is performed",
    notes:"Prevents spreading fungal and bacterial disease between plants. Keep a dip container on the truck at all times.",
    category:"spray" },
  { name:"Vinegar Sprayer (mix)", abbrev:"—", type:"Herbicide (organic)",
    npk:"N/A", use:"Weed control in hardscape cracks, gravel beds",
    rate:"Full strength or diluted per label",
    timing:"Apply on sunny days for best effect. Avoid contact with desirable plants.",
    notes:"Organic non-selective herbicide. Effective on annual weeds. Perennial weeds (bindweed) may need RoundUp.",
    category:"spray" },
  { name:"RoundUp (glyphosate)", abbrev:"RU", type:"Herbicide",
    npk:"N/A", use:"Perennial weeds: bindweed. Client-specific — check notes.",
    rate:"Per label",
    timing:"When weeds are actively growing",
    notes:"Use only where noted in client service notes. Some clients prohibit use. Apply carefully — non-selective.",
    category:"spray", warn:true },
  { name:"Sluggo",          abbrev:"—",  type:"Pest Control",
    npk:"N/A", use:"Snails and slugs — all beds",
    rate:"Scatter per label around affected plants",
    timing:"After rain or irrigation. Reapply monthly in growing season.",
    notes:"Iron phosphate formula — safe around pets and wildlife when used per label.",
    category:"spray" },
  { name:"Antifungal Spray (concentrate)", abbrev:"AF", type:"Fungicide",
    npk:"N/A", use:"Active fungal disease on foliage",
    rate:"Per label — dilute concentrate",
    timing:"At first sign of disease. Repeat per label interval.",
    notes:"Record use on client sheet. Billable charge per application.",
    category:"spray" },
];

// =============================================================